# paths = ["/path/to/override"] # path dependency overrides

[alias] # command aliases
# "I like testing"
t = "test --all-features"
rt = "run && cargo test --all-features"

[build-debug]
incremental = true # Quite a lot quicker rebuild times for the sake of binary size.

[build]
jobs = 10                          # Defaults to your CPU cores
rustdoc = "rustdoc"
target-dir = "shared_rust_target/" # Shared target-dir.
# Save on disc space for apps that require single compilation and release
# compilation in general.
incremental = false

[cargo-new]
vcs = "git" # git is the default.

[term]
quiet = false            # whether cargo output is quiet
verbose = false          # whether cargo provides verbose output
color = 'always'         # whether cargo colorizes output
hyperlinks = true        # whether cargo inserts links into output
unicode = true           # whether cargo can render output using non-ASCII unicode characters
progress.when = 'always' # whether cargo shows progress bar
progress.width = 80      # width of progress bar
