#!/bin/bash

###############################################################################
# For non-interactive bash shells
###############################################################################

# If not running interactively, don't do anything
#
# ZSH already ignores non-interactive runs by using `.zshenv` for them rather
# than `.zshrc`.
[[ $- != *i* ]] && return

###############################################################################
# The .profile config for both Bash and Zsh.
###############################################################################

source "$HOME/.profile"

###############################################################################
# Startup programs in the terminal using eval.
###############################################################################

# zoxide + fzf
# https://github.com/ajeetdsouza/zoxide
eval "$(zoxide init --cmd cd bash)"

# Starship
# https://github.com/starship/starship
eval "$(starship init bash)"

PROMPT_COMMAND="$PROFILE_PROMPT_COMMANDS; $PROMPT_COMMAND"
