# https://wiki.hyprland.org/Configuring/

# NOTE: Caelestia's app launcher uses the `global` submap.
#
# - <https://wiki.hypr.land/Configuring/Binds/#submaps>
# - <https://github.com/caelestia-dots/shell/discussions/401#discussioncomment-14077402>
exec = hyprctl dispatch submap global
submap = global

source = ./modules/animations.conf
source = ./modules/autostart.conf
source = ./modules/env.conf
source = ./modules/gestures.conf
source = ./modules/input.conf
source = ./modules/keybindings.conf
source = ./modules/look-and-feel.conf
source = ./modules/monitors.conf
# source = ./modules/programs.conf
source = ./modules/window-rules.conf
source = ./modules/workspace-rules.conf
