export DEEPSEEK_API_KEY="$(secret-tool lookup account deepseek service api key key)"
export CLAUDE_API_KEY="$(secret-tool lookup account claude service api key key)"
export CODECOV_TOKEN="$(secret-tool lookup account codecov service api key token)"
export OPENROUTER_TOKEN="$(secret-tool lookup account openrouter service api key token)"
export OPENCODE_TOKEN="$(secret-tool lookup account opencode service api key token)"
