#################
### AUTOSTART ###
#################

$XDG_DATA_DIRS="$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share"

# https://wiki.hypr.land/Configuring/Dispatchers/

exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Auto delete trash 30 days old
exec-once = trash-empty 30

# Cursors
$cursorTheme = sweet-cursors
$cursorSize = 24
exec-once = hyprctl setcursor $cursorTheme $cursorSize
exec-once = gsettings set org.gnome.desktop.interface cursor-theme '$cursorTheme'
exec-once = gsettings set org.gnome.desktop.interface cursor-size $cursorSize

# Location and night light
exec-once = /usr/lib/geoclue-2.0/demos/agent
exec-once = sleep 1 && gammastep

# Forward bluetooth media commands to MPRIS
exec-once = mpris-proxy

# Caelestia
exec-once = caelestia resizer -d
exec-once = XDG_DATA_DIRS=$XDG_DATA_DIRS caelestia shell -d

# Input methods
exec-once = fcitx5
exec-once = espanso start

exec-once = ~/dotfiles/dot-config/programs/shell_scripts/usb-device-connect.sh
