###################
### MY PROGRAMS ###
###################

# https://wiki.hypr.land/Configuring/Variables/

# Variables used for execs.

$terminal = kitty
$fileManager = nautilus -w
$menu = export XDG_DATA_DIRS=$XDG_DATA_DIRS && wofi --show drun
