####################
### WINDOW RULES ###
####################

# --- Unified Rule Definitions (The "centerfloat" Tag) ---
windowrule = float on, match:tag centerfloat
windowrule = center on, match:tag centerfloat
windowrule = size (monitor_w*0.6) (monitor_h*0.6), match:tag centerfloat

# --- Assigning the Tag to Classes ---
windowrule = tag +centerfloat, match:class ^(Thunar|org\.gnome\.Nautilus)$
windowrule = tag +centerfloat, match:class ^(floorp)$, match:title ^[Ss]ave.+
windowrule = tag +centerfloat, match:class ^(xdg-desktop-portal-gtk)$, match:title ^blob:https://discord\.com/.+
windowrule = tag +centerfloat, match:class ^(xdg-desktop-portal-gtk)$, match:title Open Files
windowrule = tag +centerfloat, match:class ^(pavucontrol)$

# --- Event Suppression and Focus ---
windowrule = suppress_event maximize, match:class .*
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false

# --- Vesktop Rules ---
windowrule {
    name = vesktop-rules
    match:class = ^([Vv]esktop)$
    float = on
    center = on
    size = (monitor_w*0.8) (monitor_h*0.8)
    opacity = 0.9
}

# --- Terminal Rules ---
windowrule {
    name = terminal
    match:class = ^[Kk]itty$
    opacity = 0.93
}

# --- Floating Terminal Rules ---
windowrule {
    name = floating-terminal
    match:class = ^(floating-term)$
    float = on
    center = on
    size = (monitor_w*0.7) (monitor_h*0.7)
    opacity = 0.9
}

# --- Spotify Rules ---
windowrule {
    name = spotify
    match:class = ^[Ss]potify$
    opacity = 0.70
}

# --- Nautilus Rules ---
windowrule {
    name = nautilus
    match:class = org\.gnome\.Nautilus
    opacity = 0.9
}

# --- Fullsceen Rules ---
windowrule {
    name = fullscreen
    match:fullscreen = 1
    opacity = 1
}
