return {

	-- tokyonight
	{
		"ntk148v/habamax.nvim",
		lazy = true,
		-- opts = { style = "" },
	},
	-- catppuccin
	{
		"catppuccin/nvim",
		lazy = true,
		name = "catppuccin",
		priority = 1000,
		transparent_background = true,
		styles = {
			functions = { "bold" },
		},
		-- credit to the original color overrides:
		--https://github.com/b-ggs/dotfiles/blob/becba14045586db9ee2becf39fbe07f0f8ae0a68/nvim/.config/nvim/init.vim#L203-L237
		opts = {
			color_overrides = {
				all = {
					text = "#e0cdf4",
					subtext1 = "#cbbade",
					subtext0 = "#b7a6c9",
					overlay2 = "#a394b3",
					overlay1 = "#8b7d9b",
					overlay0 = "#786a85",
					surface2 = "#63586f",
					surface1 = "#4e4559",
					surface0 = "#3a3144",

					base = "#080011",
					mantle = "#080010",
					crust = "#080010",
				},
			},
			highlight_overrides = {
				all = function()
					return {
						DashboardHeader = { fg = "#a143ff" },
						DashboardIcon = { fg = "#b266ff" },
						DashboardDesc = { fg = "#a289bb" },
						DashboardKey = { fg = "#b266ff" },
						DashboardFooter = { fg = "#aa54ff" },
						-- Thank god it was as easy as getting chat gippidy to make
						-- a python script for this all
						Directory = { fg = "#a750ff" },
						MoreMsg = { fg = "#a750ff" },
						Question = { fg = "#a750ff" },
						Title = { fg = "#a750ff" },
						Folded = { fg = "#a750ff" },
						FloatBorder = { fg = "#a750ff" },
						Function = { fg = "#a750ff" },
						diffChanged = { fg = "#a750ff" },
						markdownLinkText = { fg = "#a750ff" },
						NavicIconsTypeParameter = { fg = "#a750ff" },
						NavicIconsEvent = { fg = "#a750ff" },
						NavicIconsStruct = { fg = "#a750ff" },
						NavicIconsFunction = { fg = "#a750ff" },
						NavicIconsMethod = { fg = "#a750ff" },
						NavicIconsPackage = { fg = "#a750ff" },
						NavicIconsModule = { fg = "#a750ff" },
						NeogitTagDistance = { fg = "#a750ff" },
						NeogitDiffHeader = { fg = "#a750ff" },
						NeogitGraphBoldBlue = { fg = "#a750ff" },
						NeogitGraphBlue = { fg = "#a750ff" },
						NeogitGraphCyan = { fg = "#a750ff" },
						NeoTreeRootName = { fg = "#a750ff" },
						NeogitChangeModified = { fg = "#a750ff" },
						NoiceConfirmBorder = { fg = "#a750ff" },
						NeotestWinSelect = { fg = "#a750ff" },
						NeotestDir = { fg = "#a750ff" },
						NeotestFile = { fg = "#a750ff" },
						NvimTreeGitNew = { fg = "#a750ff" },
						NvimTreeEmptyFolderName = { fg = "#a750ff" },
						NvimTreeOpenedFolderName = { fg = "#a750ff" },
						NvimTreeFolderIcon = { fg = "#a750ff" },
						NvimTreeFolderName = { fg = "#a750ff" },
						MiniStatuslineInactive = { fg = "#a750ff" },
						MiniStarterItemBullet = { fg = "#a750ff" },
						MiniStarterHeader = { fg = "#a750ff" },
						qfFileName = { fg = "#a750ff" },
						htmlH2 = { fg = "#a750ff" },
						diffFile = { fg = "#a750ff" },
						GlyphPalette4 = { fg = "#a750ff" },
						TelescopeMatching = { fg = "#a750ff" },
						NavicIconsConstructor = { fg = "#a750ff" },
						NeogitFilePath = { fg = "#a750ff" },
						NeoTreeDirectoryIcon = { fg = "#a750ff" },
						NeoTreeDirectoryName = { fg = "#a750ff" },
						WhichKeyGroup = { fg = "#a750ff" },
						NeogitNotificationInfo = { fg = "#a750ff" },
						NeogitHunkHeaderHighlight = { fg = "#a750ff" },
						NotifyINFOTitle = { fg = "#a750ff" },
						NotifyINFOIcon = { fg = "#a750ff" },
						NotifyINFOBorder = { fg = "#a750ff" },
						NeogitGraphBoldCyan = { fg = "#a750ff" },
						CmpItemKindTypeParameter = { fg = "#a750ff" },
						CmpItemKindOperator = { fg = "#a750ff" },
						CmpItemKindEvent = { fg = "#a750ff" },
						CmpItemKindStruct = { fg = "#a750ff" },
						CmpItemKindFile = { fg = "#a750ff" },
						CmpItemKindModule = { fg = "#a750ff" },
						CmpItemKindFolder = { fg = "#a750ff" },
						CmpItemKindFunction = { fg = "#a750ff" },
						CmpItemKindConstructor = { fg = "#a750ff" },
						CmpItemKindMethod = { fg = "#a750ff" },
						CmpItemKind = { fg = "#a750ff" },
						RainbowDelimiterBlue = { fg = "#a750ff" },
						NeotestSkipped = { fg = "#a750ff" },
						AlphaHeader = { fg = "#a750ff" },
						NavicIconsFile = { fg = "#a750ff" },
						NavicIconsNamespace = { fg = "#a750ff" },
						DapUIStepOver = { fg = "#a750ff" },
						DapUIStepInto = { fg = "#a750ff" },
						DapUIStepBack = { fg = "#a750ff" },
						DapUIStepOut = { fg = "#a750ff" },
						lualine_a_inactive = { fg = "#a750ff" },
						lualine_b_normal = { fg = "#a750ff" },
						NoiceAttr90 = { fg = "#a750ff" },
						NoiceAttr103 = { fg = "#a750ff" },
						NoiceAttr120 = { fg = "#a750ff" },
						NoiceAttr130 = { fg = "#a750ff" },
						NoiceAttr143 = { fg = "#a750ff" },
						NoiceAttr194 = { fg = "#a750ff" },
						NoiceAttr214 = { fg = "#a750ff" },
						NoiceAttr221 = { fg = "#a750ff" },
						NoiceAttr283 = { fg = "#a750ff" },
						lualine_transitional_lualine_a_normal_to_lualine_c_filetype_DevIconDefault_normal = {
							fg = "#a750ff",
						},
						lualine_transitional_lualine_a_normal_to_lualine_b_normal = { fg = "#a750ff" },
						Conditional = { fg = "#a750ff" },
						Statement = { fg = "#a750ff" },
						Repeat = { fg = "#a750ff" },
						Keyword = { fg = "#a750ff" },
						Exception = { fg = "#a750ff" },
						Include = { fg = "#a750ff" },
						Macro = { fg = "#a750ff" },
						NeogitUntrackedfiles = { fg = "#a750ff" },
						NeogitRebasing = { fg = "#a750ff" },
						NeogitStashes = { fg = "#a750ff" },
						NeogitStagedchanges = { fg = "#a750ff" },
						NeogitRecentcommits = { fg = "#a750ff" },
						NeogitUnpulledchanges = { fg = "#a750ff" },
						NeogitUnmergedchanges = { fg = "#a750ff" },
						NeogitUnstagedchanges = { fg = "#a750ff" },
						NeoTreeGitUntracked = { fg = "#a750ff" },
						CmpItemKindSnippet = { fg = "#a750ff" },
						NeogitChangeRenamed = { fg = "#a750ff" },
						NeogitSectionHeader = { fg = "#a750ff" },
						DapUIType = { fg = "#a750ff" },
						MasonHighlightSecondary = { fg = "#a750ff" },
						NeotestNamespace = { fg = "#a750ff" },
						DapBreakpointRejected = { fg = "#a750ff" },
						RainbowDelimiterViolet = { fg = "#a750ff" },
						lualine_b_visual = { fg = "#a750ff" },
						lualine_x_8_normal = { fg = "#a750ff" },
						lualine_x_8_insert = { fg = "#a750ff" },
						lualine_x_8_visual = { fg = "#a750ff" },
						lualine_x_8_replace = { fg = "#a750ff" },
						lualine_x_8_command = { fg = "#a750ff" },
						lualine_x_8_terminal = { fg = "#a750ff" },
						lualine_x_8_inactive = { fg = "#a750ff" },
						lualine_a_command = { fg = "#a750ff", bg = "#080011" },
						lualine_b_command = { fg = "#a750ff", bg = "#080011" },
						lualine_a_terminal = { fg = "#a750ff", bg = "#080011" },
						lualine_b_terminal = { fg = "#a750ff", bg = "#080011" },
						lualine_a_normal = { fg = "#a750ff", bg = "#080011" },
						lualine_c_normal = { fg = "#a750ff", bg = "#080011" },
						lualine_a_insert = { fg = "#a750ff", bg = "#080011" },
						lualine_b_insert = { fg = "#a750ff", bg = "#080011" },
						lualine_c_inactive = { fg = "#a750ff", bg = "#080011" },
						lualine_b_inactive = { fg = "#a750ff", bg = "#080011" },
						lualine_a_visual = { fg = "#a750ff", bg = "#080011" },
						lualine_a_replace = { fg = "#a750ff", bg = "#080011" },
						lualine_b_replace = { fg = "#a750ff", bg = "#080011" },
						lualine_c_6_normal = { fg = "#a750ff", bg = "#080011" },
						lualine_c_6_insert = { fg = "#a750ff", bg = "#080011" },
						lualine_c_6_visual = { fg = "#a750ff", bg = "#080011" },
						lualine_c_6_replace = { fg = "#a750ff", bg = "#080011" },
						lualine_c_6_command = { fg = "#a750ff", bg = "#080011" },
						lualine_c_6_terminal = { fg = "#a750ff", bg = "#080011" },
						lualine_c_6_inactive = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_error_normal = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_error_insert = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_error_visual = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_error_replace = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_error_command = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_error_terminal = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_error_inactive = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_warn_normal = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_warn_insert = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_warn_visual = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_warn_replace = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_warn_command = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_warn_terminal = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_warn_inactive = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_info_normal = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_info_insert = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_info_visual = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_info_replace = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_info_command = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_info_terminal = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_info_inactive = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_hint_normal = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_hint_insert = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_hint_visual = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_hint_replace = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_hint_command = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_hint_terminal = { fg = "#a750ff", bg = "#080011" },
						lualine_c_diagnostics_hint_inactive = { fg = "#a750ff", bg = "#080011" },
						lualine_x_10_normal = { fg = "#a750ff", bg = "#080011" },
						lualine_x_10_insert = { fg = "#a750ff", bg = "#080011" },
						lualine_x_10_visual = { fg = "#a750ff", bg = "#080011" },
						lualine_x_10_replace = { fg = "#a750ff", bg = "#080011" },
						lualine_x_10_command = { fg = "#a750ff", bg = "#080011" },
						lualine_x_10_terminal = { fg = "#a750ff", bg = "#080011" },
						lualine_x_10_inactive = { fg = "#a750ff", bg = "#080011" },
						lualine_x_11_normal = { fg = "#a750ff", bg = "#080011" },
						lualine_x_11_insert = { fg = "#a750ff", bg = "#080011" },
						lualine_x_11_visual = { fg = "#a750ff", bg = "#080011" },
						lualine_x_11_replace = { fg = "#a750ff", bg = "#080011" },
						lualine_x_11_command = { fg = "#a750ff", bg = "#080011" },
						lualine_x_11_terminal = { fg = "#a750ff", bg = "#080011" },
						lualine_x_11_inactive = { fg = "#a750ff", bg = "#080011" },
						lualine_x_13_normal = { fg = "#a750ff", bg = "#080011" },
						lualine_x_13_insert = { fg = "#a750ff", bg = "#080011" },
						lualine_x_13_visual = { fg = "#a750ff", bg = "#080011" },
						lualine_x_13_replace = { fg = "#a750ff", bg = "#080011" },
						lualine_x_13_command = { fg = "#a750ff", bg = "#080011" },
						lualine_x_13_terminal = { fg = "#a750ff", bg = "#080011" },
						lualine_x_13_inactive = { fg = "#a750ff", bg = "#080011" },
						lualine_x_diff_added_normal = { fg = "#a750ff", bg = "#080011" },
						lualine_x_diff_added_insert = { fg = "#a750ff", bg = "#080011" },
						lualine_x_diff_added_visual = { fg = "#a750ff", bg = "#080011" },
						lualine_x_diff_added_replace = { fg = "#a750ff", bg = "#080011" },
						lualine_x_diff_added_command = { fg = "#a750ff", bg = "#080011" },
						lualine_x_diff_added_terminal = { fg = "#a750ff", bg = "#080011" },
						lualine_x_diff_added_inactive = { fg = "#a750ff", bg = "#080011" },
						lualine_x_diff_modified_normal = { fg = "#a750ff", bg = "#080011" },
						lualine_x_diff_modified_insert = { fg = "#a750ff", bg = "#080011" },
						lualine_x_diff_modified_visual = { fg = "#a750ff", bg = "#080011" },
						lualine_x_diff_modified_replace = { fg = "#a750ff", bg = "#080011" },
						lualine_x_diff_modified_command = { fg = "#a750ff", bg = "#080011" },
						lualine_x_diff_modified_terminal = { fg = "#a750ff", bg = "#080011" },
						lualine_x_diff_modified_inactive = { fg = "#a750ff", bg = "#080011" },
						lualine_x_diff_removed_normal = { fg = "#a750ff", bg = "#080011" },
						lualine_x_diff_removed_insert = { fg = "#a750ff", bg = "#080011" },
						lualine_x_diff_removed_visual = { fg = "#a750ff", bg = "#080011" },
						lualine_x_diff_removed_replace = { fg = "#a750ff", bg = "#080011" },
						lualine_x_diff_removed_command = { fg = "#a750ff", bg = "#080011" },
						lualine_x_diff_removed_terminal = { fg = "#a750ff", bg = "#080011" },
						lualine_x_diff_removed_inactive = { fg = "#a750ff", bg = "#080011" },
						-- Operator = { fg="FF5050" }
						Normal = { fg = "#c289fb", bg = "#080011" },
						LineNr = { fg = "#9958da" },
						Pmenu = { fg = "#9958da" },
						CursorLineNr = { fg = "#7f00ff" },
						Comment = { fg = "#d9b3ff" },
					}
				end,
			},
			mode_colors = {
				["n"] = { "NORMAL", "#a750ff" },
				["no"] = { "N-PENDING", "#a750ff" },
				["i"] = { "INSERT", "#a750ff" },
				["ic"] = { "INSERT", "#a750ff" },
				["t"] = { "TERMINAL", "#a750ff" },
				["v"] = { "VISUAL", "#a750ff" },
				["V"] = { "V-LINE", "#a750ff" },
				[""] = { "V-BLOCK", "#a750ff" },
				["R"] = { "REPLACE", "#a750ff" },
				["Rv"] = { "V-REPLACE", "#a750ff" },
				["s"] = { "SELECT", "#a750ff" },
				["S"] = { "S-LINE", "#a750ff" },
				[""] = { "S-BLOCK", "#a750ff" },
				["c"] = { "COMMAND", "#a750ff" },
				["cv"] = { "COMMAND", "#a750ff" },
				["ce"] = { "COMMAND", "#a750ff" },
				["r"] = { "PROMPT", "#a750ff" },
				["rm"] = { "MORE", "#a750ff" },
				["r?"] = { "CONFIRM", "#a750ff" },
				["!"] = { "SHELL", "#a750ff" },
			},
			integrations = {
				aerial = true,
				alpha = true,
				cmp = true,
				dashboard = true,
				flash = true,
				gitsigns = true,
				headlines = true,
				illuminate = true,
				indent_blankline = { enabled = true },
				leap = true,
				lsp_trouble = true,
				mason = true,
				markdown = true,
				mini = true,
				native_lsp = {
					enabled = true,
					underlines = {
						errors = { "undercurl" },
						hints = { "undercurl" },
						warnings = { "undercurl" },
						information = { "undercurl" },
					},
				},
				navic = { enabled = true, custom_bg = "lualine" },
				neotest = true,
				neotree = true,
				noice = true,
				notify = true,
				semantic_tokens = true,
				telescope = true,
				treesitter = true,
				treesitter_context = true,
				which_key = true,
			},
		},
	},
}
