return {

	-- tokyonight
	{
		"ntk148v/habamax.nvim",
		lazy = true,
		-- opts = { style = "" },
	},
	-- catppuccin
	{
		"catppuccin/nvim",
		lazy = true,
		name = "catppuccin",
		priority = 1000,
		transparent_background = true,
		styles = {
			functions = { "bold" },
		},
		-- credit to the original color overrides:
		--https://github.com/b-ggs/dotfiles/blob/becba14045586db9ee2becf39fbe07f0f8ae0a68/nvim/.config/nvim/init.vim#L203-L237
		opts = {
			color_overrides = {
				all = {
					text = "#F4CDCD",
					subtext1 = "#DEBABA",
					subtext0 = "#C9A6A6",
					overlay2 = "#B39494",
					overlay1 = "#9B7D7D",
					overlay0 = "#856B6B",
					surface2 = "#6F5858",
					surface1 = "#594545",
					surface0 = "#443131",

					base = "#110000",
					mantle = "#100000",
					crust = "#100000",
				},
			},
			highlight_overrides = {
				all = function()
					return {
						DashboardHeader = { fg = "#FF4444" },
						DashboardIcon = { fg = "#FF6666" },
						DashboardDesc = { fg = "#BB8989" },
						DashboardKey = { fg = "#FF6666" },
						DashboardFooter = { fg = "#FF5555" },
						-- Thank god it was as easy as getting chat gippidy to make
						-- a python script for this all
						Directory = { fg = "#FF5050" },
						MoreMsg = { fg = "#FF5050" },
						Question = { fg = "#FF5050" },
						Title = { fg = "#FF5050" },
						Folded = { fg = "#FF5050" },
						FloatBorder = { fg = "#FF5050" },
						Function = { fg = "#FF5050" },
						diffChanged = { fg = "#FF5050" },
						markdownLinkText = { fg = "#FF5050" },
						NavicIconsTypeParameter = { fg = "#FF5050" },
						NavicIconsEvent = { fg = "#FF5050" },
						NavicIconsStruct = { fg = "#FF5050" },
						NavicIconsFunction = { fg = "#FF5050" },
						NavicIconsMethod = { fg = "#FF5050" },
						NavicIconsPackage = { fg = "#FF5050" },
						NavicIconsModule = { fg = "#FF5050" },
						NeogitTagDistance = { fg = "#FF5050" },
						NeogitDiffHeader = { fg = "#FF5050" },
						NeogitGraphBoldBlue = { fg = "#FF5050" },
						NeogitGraphBlue = { fg = "#FF5050" },
						NeogitGraphCyan = { fg = "#FF5050" },
						NeoTreeRootName = { fg = "#FF5050" },
						NeogitChangeModified = { fg = "#FF5050" },
						NoiceConfirmBorder = { fg = "#FF5050" },
						NeotestWinSelect = { fg = "#FF5050" },
						NeotestDir = { fg = "#FF5050" },
						NeotestFile = { fg = "#FF5050" },
						NvimTreeGitNew = { fg = "#FF5050" },
						NvimTreeEmptyFolderName = { fg = "#FF5050" },
						NvimTreeOpenedFolderName = { fg = "#FF5050" },
						NvimTreeFolderIcon = { fg = "#FF5050" },
						NvimTreeFolderName = { fg = "#FF5050" },
						MiniStatuslineInactive = { fg = "#FF5050" },
						MiniStarterItemBullet = { fg = "#FF5050" },
						MiniStarterHeader = { fg = "#FF5050" },
						qfFileName = { fg = "#FF5050" },
						htmlH2 = { fg = "#FF5050" },
						diffFile = { fg = "#FF5050" },
						GlyphPalette4 = { fg = "#FF5050" },
						TelescopeMatching = { fg = "#FF5050" },
						NavicIconsConstructor = { fg = "#FF5050" },
						NeogitFilePath = { fg = "#FF5050" },
						NeoTreeDirectoryIcon = { fg = "#FF5050" },
						NeoTreeDirectoryName = { fg = "#FF5050" },
						WhichKeyGroup = { fg = "#FF5050" },
						NeogitNotificationInfo = { fg = "#FF5050" },
						NeogitHunkHeaderHighlight = { fg = "#FF5050" },
						NotifyINFOTitle = { fg = "#FF5050" },
						NotifyINFOIcon = { fg = "#FF5050" },
						NotifyINFOBorder = { fg = "#FF5050" },
						NeogitGraphBoldCyan = { fg = "#FF5050" },
						CmpItemKindTypeParameter = { fg = "#FF5050" },
						CmpItemKindOperator = { fg = "#FF5050" },
						CmpItemKindEvent = { fg = "#FF5050" },
						CmpItemKindStruct = { fg = "#FF5050" },
						CmpItemKindFile = { fg = "#FF5050" },
						CmpItemKindModule = { fg = "#FF5050" },
						CmpItemKindFolder = { fg = "#FF5050" },
						CmpItemKindFunction = { fg = "#FF5050" },
						CmpItemKindConstructor = { fg = "#FF5050" },
						CmpItemKindMethod = { fg = "#FF5050" },
						CmpItemKind = { fg = "#FF5050" },
						RainbowDelimiterBlue = { fg = "#FF5050" },
						NeotestSkipped = { fg = "#FF5050" },
						AlphaHeader = { fg = "#FF5050" },
						NavicIconsFile = { fg = "#FF5050" },
						NavicIconsNamespace = { fg = "#FF5050" },
						DapUIStepOver = { fg = "#FF5050" },
						DapUIStepInto = { fg = "#FF5050" },
						DapUIStepBack = { fg = "#FF5050" },
						DapUIStepOut = { fg = "#FF5050" },
						lualine_a_inactive = { fg = "#FF5050" },
						lualine_b_normal = { fg = "#FF5050" },
						NoiceAttr90 = { fg = "#FF5050" },
						NoiceAttr103 = { fg = "#FF5050" },
						NoiceAttr120 = { fg = "#FF5050" },
						NoiceAttr130 = { fg = "#FF5050" },
						NoiceAttr143 = { fg = "#FF5050" },
						NoiceAttr194 = { fg = "#FF5050" },
						NoiceAttr214 = { fg = "#FF5050" },
						NoiceAttr221 = { fg = "#FF5050" },
						NoiceAttr283 = { fg = "#FF5050" },
						lualine_transitional_lualine_a_normal_to_lualine_c_filetype_DevIconDefault_normal = {
							fg = "#FF5050",
						},
						lualine_transitional_lualine_a_normal_to_lualine_b_normal = { fg = "#FF5050" },
						Normal = { fg = "#FB8989" },
						LineNr = { fg = "#DA5858" },
						Pmenu = { fg = "#DA5858" },
						CursorLineNr = { fg = "#FF0000" },
						Comment = { fg = "#990000" },
					}
				end,
			},
			integrations = {
				aerial = true,
				alpha = true,
				cmp = true,
				dashboard = true,
				flash = true,
				gitsigns = true,
				headlines = true,
				illuminate = true,
				indent_blankline = { enabled = true },
				leap = true,
				lsp_trouble = true,
				mason = true,
				markdown = true,
				mini = true,
				native_lsp = {
					enabled = true,
					underlines = {
						errors = { "undercurl" },
						hints = { "undercurl" },
						warnings = { "undercurl" },
						information = { "undercurl" },
					},
				},
				navic = { enabled = true, custom_bg = "lualine" },
				neotest = true,
				neotree = true,
				noice = true,
				notify = true,
				semantic_tokens = true,
				telescope = true,
				treesitter = true,
				treesitter_context = true,
				which_key = true,
			},
		},
	},
}
